/**
 * script/generate-bundled-skills.ts
 * 
 * Generates a TypeScript file with all skills from antigravity-awesome-skills
 * bundled as BuiltinSkill objects.
 * 
 * Usage: bun run script/generate-bundled-skills.ts
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { join, basename } from "node:path";
import { execSync } from "node:child_process";
import { tmpdir } from "node:os";

const SKILLS_REPO = "https://github.com/sickn33/antigravity-awesome-skills.git";
const OUTPUT_FILE = join(import.meta.dir, "../src/features/bundled-skills/generated-skills.ts");

interface SkillFrontmatter {
    name?: string;
    description?: string;
    "argument-hint"?: string;
    model?: string;
    agent?: string;
    subtask?: boolean;
}

function parseFrontmatter(content: string): { data: SkillFrontmatter; body: string } {
    const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
    if (!frontmatterMatch) {
        return { data: {}, body: content };
    }

    const yamlContent = frontmatterMatch[1];
    const body = frontmatterMatch[2];
    const data: SkillFrontmatter = {};

    // Simple YAML parsing
    for (const line of yamlContent.split("\n")) {
        const match = line.match(/^(\w[\w-]*?):\s*(.*)$/);
        if (match) {
            const key = match[1] as keyof SkillFrontmatter;
            const value = match[2].replace(/^["']|["']$/g, "");
            if (key === "subtask") {
                data[key] = value === "true";
            } else {
                (data as any)[key] = value;
            }
        }
    }

    return { data, body };
}

function escapeForTemplate(str: string): string {
    return str
        .replace(/\\/g, "\\\\")
        .replace(/`/g, "\\`")
        .replace(/\$/g, "\\$");
}

async function main() {
    console.log("🔧 Generating bundled skills...");

    // Clone repo to temp directory
    const tempDir = join(tmpdir(), "antigravity-skills-" + Date.now());
    console.log(`📥 Cloning skills repo to ${tempDir}...`);

    try {
        execSync(`git clone --depth 1 ${SKILLS_REPO} ${tempDir}`, { stdio: "pipe" });
    } catch (error) {
        console.error("Failed to clone repo:", error);
        process.exit(1);
    }

    const skillsDir = join(tempDir, "skills");
    if (!existsSync(skillsDir)) {
        console.error("Skills directory not found in repo");
        process.exit(1);
    }

    // Read all skills
    const skillFolders = readdirSync(skillsDir, { withFileTypes: true })
        .filter(d => d.isDirectory())
        .map(d => d.name);

    console.log(`📚 Found ${skillFolders.length} skill folders`);

    const skills: Array<{
        name: string;
        description: string;
        template: string;
        argumentHint?: string;
        model?: string;
        agent?: string;
        subtask?: boolean;
    }> = [];

    for (const folder of skillFolders) {
        const skillMdPath = join(skillsDir, folder, "SKILL.md");
        if (!existsSync(skillMdPath)) continue;

        try {
            const content = readFileSync(skillMdPath, "utf-8");
            const { data, body } = parseFrontmatter(content);

            skills.push({
                name: data.name || folder,
                description: data.description || "",
                template: body.trim(),
                argumentHint: data["argument-hint"],
                model: data.model,
                agent: data.agent,
                subtask: data.subtask,
            });
        } catch (error) {
            console.warn(`⚠️ Failed to parse ${folder}/SKILL.md:`, error);
        }
    }

    console.log(`✅ Parsed ${skills.length} skills`);

    // Generate TypeScript
    const outputDir = join(import.meta.dir, "../src/features/bundled-skills");
    if (!existsSync(outputDir)) {
        mkdirSync(outputDir, { recursive: true });
    }

    const tsContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: bun run script/generate-bundled-skills.ts
 * Generated at: ${new Date().toISOString()}
 * Total skills: ${skills.length}
 */

import type { BuiltinSkill } from "../builtin-skills/types";

export const generatedSkills: BuiltinSkill[] = [
${skills.map(skill => `  {
    name: "${skill.name}",
    description: ${JSON.stringify(skill.description)},
    template: \`${escapeForTemplate(skill.template)}\`,${skill.argumentHint ? `\n    argumentHint: ${JSON.stringify(skill.argumentHint)},` : ""}${skill.model ? `\n    model: ${JSON.stringify(skill.model)},` : ""}${skill.agent ? `\n    agent: ${JSON.stringify(skill.agent)},` : ""}${skill.subtask ? `\n    subtask: true,` : ""}
  }`).join(",\n")}
];

export function getBundledSkillsCount(): number {
  return generatedSkills.length;
}
`;

    writeFileSync(OUTPUT_FILE, tsContent);
    console.log(`📝 Generated ${OUTPUT_FILE}`);

    // Cleanup temp directory
    rmSync(tempDir, { recursive: true, force: true });
    console.log(`🧹 Cleaned up temp directory`);

    console.log(`\n✨ Done! Generated ${skills.length} bundled skills.`);
}

main();
